export const maPrimeRenovData = {
    province:{
        "one":{
            bleu:{
                min:0,
                max:15262,
            },
            jaune:{
                min:15262,
                max:19565,
            },
            violet:{
                min:19565,
                max:29168
            },
            rose:{
                min:29168,
            }
        },
        "two":{
            bleu:{
                min:0,
                max:22310,
            },
            jaune:{
                min:22310,
                max:28614,
            },
            violet:{
                min:28614,
                max:42848
            },
            rose:{
                min:42848
            }
        },
        "three":{
            bleu:{
                min:0,
                max:26844,
            },
            jaune:{
                min:26844,
                max:34411,
            },
            violet:{
                min:34411,
                max:51592
            },
            rose:{
                min:51592,
            }
        },
        "four":{
            bleu:{
                min:0,
                max:31359,
            },
            jaune:{
                min:31359,
                max:40201,
            },
            violet:{
                min:40201,
                max:60336
            },
            rose:{
                min:60336,
            }
        }, 
        "five":{
            bleu:{
                min:0,
                max:35894,
            },
            jaune:{
                min:35894,
                max:46015,
            },
            violet:{
                min:46015,
                max:69081
            },
            rose:{
                min:69081,
            }
        },
        "+five":{}
    },
    ileDeFrance:{
        "one":{
            bleu:{
                min:0,
                max:21123,
            },
            jaune:{
                min:21123,
                max:25714,
            },
            violet:{
                min:25714,
                max:38184
            },
            rose:{
                min:38184,
            }
        },
        "two":{
            bleu:{
                min:0,
                max:31003,
            },
            jaune:{
                min:31003,
                max:37739,
            },
            violet:{
                min:37739,
                max:56130
            },
            rose:{
                min:56130,
            }
        },
        "three":{
            bleu:{
                min:0,
                max:37232,
            },
            jaune:{
                min:37232,
                max:45326,
            },
            violet:{
                min:45326,
                max:67585
            },
            rose:{
                min:67585,
            }
        },
        "four":{
            bleu:{
                min:0,
                max:43472,
            },
            jaune:{
                min:43472,
                max:52925,
            },
            violet:{
                min:52925,
                max:79041
            },
            rose:{
                min:79041,
            }
        }, 
        "five":{
            bleu:{
                min:0,
                max:49736,
            },
            jaune:{
                min:49736,
                max:60546,
            },
            violet:{
                min:60546,
                max:90496
            },
            rose:{
                min:90496,
            }
        },
        "+five":{}
    }
}