export const maPrimeRenovData = {
    province:{
        "one":{
            bleu:{
                min:0,
                max:15262,
            },
            jaune:{
                min:15262,
                max:19565,
            },
            violet:{
                min:19565,
                max:29168
            },
            rose:{
                min:29168,
            }
        },
        "two":{
            bleu:{
                min:0,
                max:22310,
            },
            jaune:{
                min:22310,
                max:28614,
            },
            violet:{
                min:28614,
                max:42848
            },
            rose:{
                min:42848
            }
        },
        "three":{
            bleu:{
                min:0,
                max:26844,
            },
            jaune:{
                min:26844,
                max:34411,
            },
            violet:{
                min:34411,
                max:51592
            },
            rose:{
                min:51592,
            }
        },
        "four":{
            bleu:{
                min:0,
                max:31359,
            },
            jaune:{
                min:31359,
                max:40201,
            },
            violet:{
                min:40201,
                max:60336
            },
            rose:{
                min:60336,
            }
        }, 
        "five":{
            bleu:{
                min:0,
                max:35894,
            },
            jaune:{
                min:35894,
                max:46015,
            },
            violet:{
                min:46015,
                max:69081
            },
            rose:{
                min:69081,
            }
        },
        "six":{
            bleu:{
                min:0,
                max:40420,
            },
            jaune:{
                min:40420,
                max:51812,
            },
            violet:{
                min:51812,
                max:77825
            },
            rose:{
                min:77825,
            }
        },
        "seven":{
            bleu:{
                min:0,
                max:44946,
            },
            jaune:{
                min:44946,
                max:57609,
            },
            violet:{
                min:57609,
                max:86569
            },
            rose:{
                min:86569,
            }
        },
        "eight":{
            bleu:{
                min:0,
                max:49472,
            },
            jaune:{
                min:49472,
                max:63406,
            },
            violet:{
                min:63406,
                max:95313
            },
            rose:{
                min:95313,
            }         
        },
        "nine":{
            bleu:{
                min:0,
                max:53998,
            },
            jaune:{
                min:53998,
                max:69203,
            },
            violet:{
                min:69203,
                max:104057
            },
            rose:{
                min:104057,
            }         
        },
        "ten":{
            bleu:{
                min:0,
                max:58524,
            },
            jaune:{
                min:58524,
                max:75000,
            },
            violet:{
                min:75000,
                max:112901
            },
            rose:{
                min:112901,
            }         
        },
        "eleven":{
            bleu:{
                min:0,
                max:63050,
            },
            jaune:{
                min:63050,
                max:80797,
            },
            violet:{
                min:80797,
                max:121645
            },
            rose:{
                min:121645,
            }        
        },
        "twelve":{
            bleu:{
                min:0,
                max:67576,
            },
            jaune:{
                min:67576,
                max:86594,
            },
            violet:{
                min:86594,
                max:130389
            },
            rose:{
                min:130389,
            }      
        },
        "thirteen":{
            bleu:{
                min:0,
                max:72102,
            },
            jaune:{
                min:72102,
                max:92391,
            },
            violet:{
                min:92391,
                max:139133
            },
            rose:{
                min:139133,
            }              
        },
        "fourteen":{
            bleu:{
                min:0,
                max:76628,
            },
            jaune:{
                min:76628,
                max:98188,
            },
            violet:{
                min:98188,
                max:147877
            },
            rose:{
                min:147877,
            }         
        },
        "fiveteen":{
            bleu:{
                min:0,
                max:81154,
            },
            jaune:{
                min:81154,
                max:103985,
            },
            violet:{
                min:103985,
                max:156621
            },
            rose:{
                min:156621,
            }            
        }
    },
    ileDeFrance:{
        "one":{
            bleu:{
                min:0,
                max:21123,
            },
            jaune:{
                min:21123,
                max:25714,
            },
            violet:{
                min:25714,
                max:38184
            },
            rose:{
                min:38184,
            }
        },
        "two":{
            bleu:{
                min:0,
                max:31003,
            },
            jaune:{
                min:31003,
                max:37739,
            },
            violet:{
                min:37739,
                max:56130
            },
            rose:{
                min:56130,
            }
        },
        "three":{
            bleu:{
                min:0,
                max:37232,
            },
            jaune:{
                min:37232,
                max:45326,
            },
            violet:{
                min:45326,
                max:67585
            },
            rose:{
                min:67585,
            }
        },
        "four":{
            bleu:{
                min:0,
                max:43472,
            },
            jaune:{
                min:43472,
                max:52925,
            },
            violet:{
                min:52925,
                max:79041
            },
            rose:{
                min:79041,
            }
        }, 
        "five":{
            bleu:{
                min:0,
                max:49736,
            },
            jaune:{
                min:49736,
                max:60546,
            },
            violet:{
                min:60546,
                max:90496
            },
            rose:{
                min:90496,
            }
        },
        "sixe":{
            bleu:{
                min:0,
                max:55989,
            },
            jaune:{
                min:55989,
                max:68159,
            },
            violet:{
                min:68159,
                max:101951
            },
            rose:{
                min:101951,
            }
        },
        "seven":{
            bleu:{
                min:0,
                max:62242,
            },
            jaune:{
                min:62242,
                max:75772,
            },
            violet:{
                min:75772,
                max:113406
            },
            rose:{
                min:113406,
            }      
        },
        "eight":{
            bleu:{
                min:0,
                max:68698,
            },
            jaune:{
                min:68698,
                max:83385,
            },
            violet:{
                min:83385,
                max:124861
            },
            rose:{
                min:124861,
            }            
        },
        "nine":{
            bleu:{
                min:0,
                max:74951,
            },
            jaune:{
                min:74951,
                max:90998,
            },
            violet:{
                min:90998,
                max:136316
            },
            rose:{
                min:136316,
            }                 
        },
        "ten":{
            bleu:{
                min:0,
                max:81204,
            },
            jaune:{
                min:81204,
                max:98611,
            },
            violet:{
                min:98611,
                max:147771
            },
            rose:{
                min:147771,
            }              
        },
        "eleven":{
            bleu:{
                min:0,
                max:87457,
            },
            jaune:{
                min:87457,
                max:106224,
            },
            violet:{
                min:106224,
                max:159226
            },
            rose:{
                min:159226,
            }           
        },
        "twelve":{
            bleu:{
                min:0,
                max:93719,
            },
            jaune:{
                min:93719,
                max:113837,
            },
            violet:{
                min:113837,
                max:170681
            },
            rose:{
                min:170681,
            }           
        },
        "thirteen":{
            bleu:{
                min:0,
                max:99972,
            },
            jaune:{
                min:99972,
                max:121450,
            },
            violet:{
                min:121450,
                max:182136
            },
            rose:{
                min:182136,
            }           
        },
        "fourteen":{
            bleu:{
                min:0,
                max:106225,
            },
            jaune:{
                min:106225,
                max:129063,
            },
            violet:{
                min:129063,
                max:193581
            },
            rose:{
                min:193581,
            }              
        },
        "fiveteen":{
            bleu:{
                min:0,
                max:112478,
            },
            jaune:{
                min:112478,
                max:136676,
            },
            violet:{
                min:136676,
                max:205036
            },
            rose:{
                min:205036,
            }  
        }      
    }
}